# Generated by Django 6.0.4 on 2026-09-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
    ]
