# Generated by Django 6.0.4 on 2026-07-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
